<a href="https://colab.research.google.com/github/Sowmya-2348562/Quantum-Computing/blob/main/2348562_QC_Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install qiskit


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 24.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.4/119.4 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 40.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 MB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.5/108.5 kB 3.6 MB/s eta 0:00:00


1. Tensor Product of Two Vectors
Explanation
In quantum computing, the tensor product (also known as the Kronecker product) combines two quantum states (vectors) into a single joint state. If you have two vectors:

∣
𝜓
⟩
=
[
𝑎
𝑏
]
,
∣
𝜙
⟩
=
[
𝑐
𝑑
]
∣ψ⟩=[
a
b
​
 ],∣ϕ⟩=[
c
d
​
 ]
Their tensor product
∣
𝜓
⟩
⊗
∣
𝜙
⟩
∣ψ⟩⊗∣ϕ⟩ is:

∣
𝜓
⟩
⊗
∣
𝜙
⟩
=
[
𝑎
⋅
𝑐
𝑎
⋅
𝑑
𝑏
⋅
𝑐
𝑏
⋅
𝑑
]
∣ψ⟩⊗∣ϕ⟩=
​
  
a⋅c
a⋅d
b⋅c
b⋅d
​
  
​



In [2]:
import numpy as np
from qiskit.quantum_info import Statevector, Operator

# Define two single-qubit states
psi = np.array([1, 0])  # |0>
phi = (1/np.sqrt(2)) * np.array([1, 1])  # |+>

# Tensor product
tensor_product = np.kron(psi, phi)
print("Tensor Product |0> ⊗ |+>:")
print(tensor_product)


Tensor Product |0> ⊗ |+>:
[0.70710678 0.70710678 0.         0.        ]


2. Creating an Operator and Executing on a State Vector
Explanation
A quantum operator is a matrix that acts on a quantum state vector to transform it. For example, the Pauli-X gate flips the state
∣
0
⟩
∣0⟩ to
∣
1
⟩
∣1⟩ and vice versa.

Example
Let's create the Pauli-X operator and apply it to the state
∣
+
⟩
∣+⟩.

𝑋
=
[
0
1
1
0
]
,
∣
+
⟩
=
1
2
[
1
1
]
X=[
0
1
​
  
1
0
​
 ],∣+⟩=
2
​

1
​
 [
1
1
​
 ]
Applying
𝑋
X to
∣
+
⟩
∣+⟩:

𝑋
∣
+
⟩
=
1
2
[
0
⋅
1
+
1
⋅
1
1
⋅
1
+
0
⋅
1
]
=
1
2
[
1
1
]
=
∣
+
⟩
X∣+⟩=
2
​

1
​
 [
0⋅1+1⋅1
1⋅1+0⋅1
​
 ]=
2
​

1
​
 [
1
1
​
 ]=∣+⟩

In [3]:
from qiskit.quantum_info import Operator, Statevector

# Define the Pauli-X operator
X = Operator([[0, 1],
             [1, 0]])

# Define the |+> state
plus_state = Statevector([1/np.sqrt(2), 1/np.sqrt(2)])

# Apply X operator to |+>
new_state = X @ plus_state.data
print("State after applying Pauli-X to |+>:")
print(new_state)


State after applying Pauli-X to |+>:
Operator([0.70710678+0.j, 0.70710678+0.j],
         input_dims=(), output_dims=(2,))


1. Tensor Product of Two Vectors

In [15]:
import numpy as np

# 1. Tensor Product of Two Vectors

def tensor_product(vec1, vec2):
    return np.kron(vec1, vec2)

# Example vectors
psi = np.array([1, 0])  # |0⟩
phi = np.array([1/np.sqrt(2), 1/np.sqrt(2)])  # |+⟩

# Calculate the tensor product
result = tensor_product(psi, phi)
print("Tensor Product |ψ⟩ ⊗ |ϕ⟩:")
print(result)


Tensor Product |ψ⟩ ⊗ |ϕ⟩:
[0.70710678 0.70710678 0.         0.        ]


Inference:

The tensor product of the states |0⟩ and |+⟩ produces a 4-dimensional vector representing the combined state of two qubits.
The resulting state can be interpreted as having a probability amplitude of
1/sqrt(2)
  for being in |00⟩ and |01⟩, and zero amplitude for |10⟩ and |11⟩.

2. Create an Operator and Execute on State Vector

In [16]:
# 2. Create an Operator and Execute on State Vector

# Define a simple operator (e.g., Pauli-X operator)
X_operator = np.array([[0, 1],
                       [1, 0]])

# Execute the operator on the state vector |ψ⟩
new_state = X_operator @ psi
print("\nNew State after applying X operator on |0⟩:")
print(new_state)


New State after applying X operator on |0⟩:
[0 1]


Inference:

The Pauli-X operator, which is equivalent to a NOT gate, flips the |0⟩ state to |1⟩. This demonstrates how operators can change the state of qubits, which is fundamental in quantum computation.

3. Partial Measurement

In [18]:
# 3. Partial Measurement

def partial_measure(state, index):
    # For simplicity, we consider only measurement of a single qubit
    if index == 0:  # Measure the first qubit
        return np.array([state[0], state[2]]), np.array([state[1], state[3]])
    else:  # Measure the second qubit
        return np.array([state[0], state[1]]), np.array([state[2], state[3]])

# Get the measurement results
measured_0, measured_1 = partial_measure(result, 0)
print("\nPartial Measurement Results (Measurement on first qubit):")
print("Measured |0⟩ state:", measured_0)
print("Measured |1⟩ state:", measured_1)


Partial Measurement Results (Measurement on first qubit):
Measured |0⟩ state: [0.70710678 0.        ]
Measured |1⟩ state: [0.70710678 0.        ]


Inference:

The function simulates measuring the first qubit of the combined state.
The outputs indicate the remaining states if the measurement collapses the system to |0⟩ or |1⟩. The measured states retain the amplitudes corresponding to the original state, reflecting how quantum measurement affects states.

In [19]:
# 4. CSWAP and Toffoli Gates

# CSWAP Gate
CSWAP = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 1, 0, 0],
                  [0, 0, 0, 0, 1, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 1],
                  [0, 0, 0, 0, 0, 0, 1, 0]])

print("\nCSWAP Matrix Representation:")
print(CSWAP)

# Toffoli Gate
Toffoli = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                    [0, 1, 0, 0, 0, 0, 0, 0],
                    [0, 0, 1, 0, 0, 0, 0, 0],
                    [0, 0, 0, 1, 0, 0, 0, 0],
                    [0, 0, 0, 0, 1, 0, 0, 0],
                    [0, 0, 0, 0, 0, 1, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 1],
                    [0, 0, 0, 0, 0, 0, 1, 0]])

print("\nToffoli Matrix Representation:")
print(Toffoli)



CSWAP Matrix Representation:
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]]

Toffoli Matrix Representation:
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]]


Inference:

The CSWAP gate (Controlled-SWAP) swaps the states of two target qubits if the control qubit is in the |1⟩ state. The matrix representation shows which states are swapped based on the control qubit.
The Toffoli gate (Controlled-Controlled-NOT) flips the third qubit (target) if the first two qubits (controls) are both in the |1⟩ state. Its matrix shows the effect of conditional logic in quantum circuits.

Tensor Product:

We define the function tensor_product using NumPy's kron function to compute the tensor product of two vectors.
Operator Application:

We define a simple Pauli-X operator and apply it to the |0⟩ state vector using matrix multiplication.
Partial Measurement:

The partial_measure function simulates measuring one of the qubits in the composite state.
Gate Representations:

The CSWAP and Toffoli gates are defined as 8x8 matrices to represent their action on 3 qubits.